marcosdosea/gcm-ufs

Calculadora.java
=> método soma implementado

AndrezaDosea/GerenciadorCliente.java
cria um novo método na classe.
=> criação de uma novo método

Marcos/Calculadora.java
nova alteração de desempenho na calculadora.
=> melhorando o desempenho da calculadora

Natan_Clovijan/ClassCrud.java
=> ClassCrud.java criada

IgorJoao/new 1.java, IgorJoao/teste.tmp, cliente, cliente.dtd, cliente.xml
Arquivos adicionado conforme solicitação da issue #66
=> Arquivo adicionados

IgorJoao/GerenciadorCliente.java
Alteração no metodo  de consulta. #66
=> Alterando de método

Natan_Clovijan/ClassCliente.java
Criação do metodo InserirCliente na classa GerenciadorCliente
=> Criação do metodo InserirCliente

IgorJoao/GerenciadorCliente.java
=> Criação da classe GerenciadorCliente. Resolve #73

IgorJoao/GerenciadorCliente.java
=> Resolves #74

AndrezaMagda/GerenciadorCliente.java
Igor aprove a criação da classe gerenciadorCliente.
=> Criação da classe GerenciadorCliente.java. Resolves #72

AndrezaMagda/GerenciadorCliente.java
Igor, aprove a criação dos novos cinco métodos na classe gerenciadorCliente.
=> Criação dos métodos na classe GerenciadorCliente.java. Resolves #75

AndrezaMagda/GerenciadorVendas.java
Acrescentei o método na classe gerenciadorVendas.
=> Criação de método na classe GerenciadorVendas.java. Resolves #76

IgorJoao/Exercício de Gerência de Configuração/GerenciadorCliente.java
@IgorSantos1996 olhe a issue #84 e veja se o que fiz no código está de acordo com o pedido.
=> criação da classe GerenciadorCliente.java conforme a issue #84

IgorJoao/Exercício de Gerência de Configuração/GerenciadorCliente.java, IgorJoao/GerenciadorVenda.java
@IgorSantos1996 criei o construtor na classe GerenciadorCliente.java verifique, por favor. conforme a issue #84
=> criação do construtor da classe.

FelipeIgorBruno/GerenciadorCliente.java, FelipeIgorBruno/GerenciadorVendas.java
crinaod classe GerenciadorVendas e chamando um metodo de GerenciadorCliente
=> criando classe GerenciadorVendas.java Fix #96

Felipe/GerenciadorCliente.java
@NatanGoes777  revise por favor o código
=> Criação de 5 métodos na classe Gerenciador Cliente - Branch issue114

Felipe/GerenciadorCliente.java
@igorb22 de uma olha da no código por favor
=> Criação da classe Gerenciador Cliente Close #113

Felipe/GerenciadorCliente.java, Felipe/GerenciadorVendas.java
@NatanGoes777  revise o código por favor
=> Criação da classe Gerenciador Vendas - Branch issue115

AndrezaMagda/GerenciadorVenda.java
Verificar a adição de  um método de GerenciadorCliente
=> Resolves #123

KamilaValeria/GerenciadorCliente.java
@valeriabarbosasi aprove a criação da classe
=> Criando a classe GerenciadorCliente.java.resolves #132

KamilaValeria/GerenciadorVendas.java
Favor verificar o método inserido
=> #131 Resolves. Adicionei o método na classe GerenciadorVendas.java

AndrezaMagda/GerenciadorVenda.java
=> Alterando class paciente

Calculadora/Calculadora.java
=> Dosea issue170

Calculadora/Calculadora.java
=> operação implementada. Resolve #193.

Calculadora_MTO/Program.cs
Solicito a revisão do método para calcular resto na classe Calculadora_MTO
=> Resolve #198 - Criação do método para calcular resto entre dois valores inteiros

GilsonCaio/GerenciadorCliente.java
Verificar se os dados estão sendo atualizados no Banco de Dados.
=> #214 - Adicao da funcionalidade de atualizar dados de um cliente

LuizMoitinho/DAOVenda.java, LuizMoitinho/GerenciadoraVenda.java
validar regra de negócio do método implementado.
=> #211 - rotina para atualizar dados de uma venda

LuizMoitinho/DAOCliente.java, LuizMoitinho/GerenciadoraCliente.java
Verificar se os dados obrigatórios estão sendo armazenados.
=> 212 - adição da classe DAOCliente e metodo para remoção de cliente

GilsonCaio/DAOCliente.java, GilsonCaio/GerenciadorCliente.java
=> #213 - Adicao da funcionalidade de remocao de cliente

Marcos/gerenciadorCliente.txt
Solicito que revise o código de alterar os dados do cliente.
=> Método de alteração de dados feita.

HenriquePrado/GerenciadorCliente.java
Solicito que revise o código de alterar dados
=> método alterar dados resolvido

HenriquePrado/GerenciadorCliente.java
solicito a revisão do código adicionar cliente
=> método adicionar cliente feito com sucesso

Marcos/gerenciadorCliente.txt
Favor, revisar o código de adicionar cliente.
=> Método de adicionar cliente criado.

LuizMoitinho/GerenciadoraCliente.java
=> Resolved #223 - adiçao do atributo CPF na classe GerenciadoraCliente

WagnerPrata/BubbleSort.java.txt
Por gentileza revisar pull request, objetivo resolução do método bolha.
=> Resolvendo método Bolha #228

WagnerPrata/InsertionSort.java.txt
Por favor revisar o código do método Insert
=> Código do método InsertionSort #229

WagnerPrata/InsertionSort.java.txt
Por favor verificar a correção do código
=> Corrigido o código Bug do InsertionSort #230

Jeovane/GerenciadorCliente.Java
=> implementação referente a issue #265

Maycon/GerenciadorVenda.java
verificar para não ser aprovado um código com erros.
=> implementação da função nova_venda #252

Maycon/inserir_cliente.java
verificar para não ser aprovado um código com erros.
=> Branches maycon251

Maycon/inserir_cliente.java
verificar codigo para não ser aprovado um código com erros.
=> Branches maycon250

Jeovane/GerenciadorCliente.Java
=> referente a issue #266

Dryele/GerenciadorVenda.java
=> Metódo efetuarVenda inserido Resolve #243.

Dryele/GerenciadorCliente.java
=> Inserido o método listar na classe GerenciadorCliente.java Resolve #242.

Andeson/Cliente.java
Favor verifique se está apto ao merge.
=> Método alterarCliente() adicionado.

Roberto/GerenciadorVendas.java
=> Branch roberto275

Roberto/GerenciadorCliente.java
=> Class implementada. Resolve #276

RafaelT/GerenciarCliente.java
=> Implementação de remove cliente Resolve #268

RafaelT/GerenciarCliente.java
=> Implementação de atualizar cliente Resolve #269

RafaelT/GerenciarVenda.java
=> Criando método para adicionar vendas Resolve #270

Wedson/GerenciadorCliente.java, Wedson/GerenciadorVenda.java
implementada a função de remoção do cliente
=> Branch wedson1

Wedson/GerenciadorCliente.java
Resolvendo função de alterar dados do cliente
=> Branch wedson2

Andeson/Cliente.java
Favor verifique se está funcionando.
=> Corrigido o problema da data fixa

Liliane/CRUD.cs, Liliane/Calculadora.cs
Favor revisar a classe gerenciador de vendas
=> Crudvendedor

ThiagoMenezes/gerenciador_cliente.java
=> implemetentação do metodo alterarCliente #330

ThiagoMenezes/gerenciador_cliente.java
=> implementação do metodo excluirCliente Resolve #332

ThiagoMenezes/Gerenciador_Venda.java
=> implementação o metodo excluiVenda Resolve #331

Adriano/GerenciadorVenda.cs
=> Bug fix/ajuste referencia

Adriano/GerenciadorCliente.cs
=> Foi criado o método para adicionar o cliente. #341

Adriano/GerenciadorCliente.cs
=> Foi implementado o método para remover cliente. #343

Gilton Carvalho/GerenciadorCliente.java
=> Gilton branch01

Gilton Carvalho/GerenciadorVendas.java
=> implementção da issue #349.

Gilton Carvalho/GerenciadorCliente.java
=> implementei a função remover cliente. issue #351.

Kamila/GerenciadorCliente.java
=> Foi criado o metodo adicionarCliente #354

Kamila/GerenciadorVenda.java
=> Foi criado o construtor gerenciadorVenda #360

Kamila/GerenciadorCliente.java
=> Foi criado o metodo para remover o cliente #363

Andeson/Cliente.java
Favor verifique se está apto ao merge.
=> Método removerCliente() adicionado.

ValériaBarbosa/GerenciadorVenda.java
Favor verificar se o método foi corretamente implementado
=> Implementado o método cadastrar produto #323

ValériaBarbosa/GerenciadorCliente.java
=> Branch valéria321

ValériaBarbosa/GerenciadorCliente.java
Por favor, revise o código @Kamila-lima
=> Implementado o método editar Cliente #322

JúniorSantos/GerenciadorCliente.java
Favor revisar o método para remover cliente.
=> Resolvendo issue_375

JúniorSantos/GerenciadorVenda.java
favor revisar a criacao do metodo para adicioar venda
=> Resolvendo a issue 376

JúniorSantos/GerenciadorVenda.java
Favor revisar o método de atualizar status da venda.
=> Resolvendo issue_377

Dosea.txt
Foi implementada as alterações da issue #418
=> Resolução da issue #418

DoseaJessica/Calculadora.java, teste.txt.txt
No arquivo teste, coloquei uma frase para fazer o teste do branch.
=> Testando o branch

main.java
O arquivo main foi adicionado como nos conformes.
=> Adicionado arquivo main para o projeto

Teste_Frauzo.txt
O arquivo foi devidamente criado
=> Resolução da issue #433

Jessica/GerenciadorCliente.java, Jessica/GerenciadorVenda.java
Vou ter que fazer tudo de novo porque fiz errado.
=> Resolver Issues #445

JessicaPortilio/GerenciadorCliente.java
Por favor, colegas se possível revise cuidadosamente meu pull requests, mas lembre-se do risco de aprovar um código ruim.
Se as solicitações for aprovada, por favor eu solicito que o mesmo faça a aprovação dos pull requests e exclusão da branch associada.
Desde já muito obrigada.
=> Resolvido o problema do método insert e consult issues Close #475

JessicaPortilio/GerenciadorCliente.java
Por favor, colegas se possível revise cuidadosamente meu pull requests, mas lembre-se do risco de aprovar um código ruim.
Se as solicitações for aprovada, por favor eu solicito que o mesmo faça a aprovação dos pull requests e exclusão da branch associada.
Desde já muito obrigada.
=> Foi corrigido o erro conforme foi pedido no issues Close #477

JessicaPortilio/GerenciadorVenda.java
Por favor, colegas se possível revise cuidadosamente meu pull requests, mas lembre-se do risco de aprovar um código ruim.
Se as solicitações for aprovada, por favor eu solicito que o mesmo faça a aprovação dos pull requests e exclusão da branch associada.
Desde já muito obrigada.
=> Foi feito a correção conforme pedido no issues Close #479

Frauzo/GerenciadorCliente.java.txt
Criado devidamente de acordo #487
=> Criação da classe Gereciador Cliente de acordo com #487

Frauzo/GerenciadorCliente.java.txt
Foi implementado mais funções a remover e alterar segundo #488
=> Alterações na classe GerenciadorCliente.java de vigente segundo o #488

Frauzo/GerenciadorVenda.java.txt
Foi devidamente atendido a solicitação do #489
=> Criação do novo método GerenciadorVenda.java conforme o #489

Dosea2022/Calculadora2.java
Adicionado noca classe calculadora
=> Branch dosea757

.gitignore
Reverts marcosdosea/gcm-ufs#782
=> Revert "Adicionado arquivos py #770"

ReinanMoises/GerenciadorPessoa.java
=> classe criada resolve #756

Milena/Cliente.java
=> ALterando branch

IA_garelaxxx/Código.txt
Revisar o arquivo de código no seguinte caminho: IA_garelaxxx > código.txt.
=> Branch criada com sucesso. Close #768

Vinicius/GerenciadorDisciplina.java
=> A classe GerenciadorDisciplina.java foi criada.

Samuel/GerenciadorCliente.java
=> Classe GerenciadorCliente implementada resolve#818

Samuel/removerCliente.java
=> class remove implemented

Samuel/GerenciadorVenda.java
=> Class remove client add

Samuel/GerenciadorVenda.java
Reverts marcosdosea/gcm-ufs#823
=> Revert "Class remove client add"

Gabriel/GerenciadorCliente.java
Caro revisor, por favor, revise a minha classe GerenciadorCliente.java e determine se ela atende as todos os requisitos do item A da Atividade Individual 2.
=> Branch gabriel #826

Moises/GerenciadorCliente.java, Moises/GerenciadorVenda.java
=> Branch moises864. métodos implementados

Moises/GerenciadorCliente.java
=> métodos remover e alterar implementados. resolve #862

Moises/GerenciadorCliente.java
=> classe e métodos implementados. resolve #860

Carlos Henrique/GerenciadorCliente.java
Adicionado os métodos alterar e remover na classe GerenciadorCliente. resolve #858
=> Branch carlos henrique 858

Ericles/GerenciadorCliente.cs
Verificar se o código está seguindo todos os requisitos da issue!
#866
=> Add:: classe GerenciadorCliente com método de inserir e consultar

Reinan/GerenciadorVendas.java
Reverts marcosdosea/gcm-ufs#891
=> Revert "Chamada do método remover na classe GerenciadorVendas.java. resolve #886"

Vinicius/atividadeIndividual/GerenciadorCliente.java
A tarefa já está pronta para ser revisada.
Por favor, realize a revisão desta tarefa com atenção. Para que assim, diminua as chances de gerar algum problema no ambiente de produção. 
Desde já, agradeço.
=> Implementação dos métodos "inserirCliente" e "consultarCliente" referente a issue #881

Joanne/ReadMe.md
=> Criando pasta Joanne #898

Carlos Daniel/GerenciadorClientes.java
preciso da revisão urgentemente.
=> criado class e metodos GerenciadorClientes.java. resolved #830

Carlos Daniel/GerenciadorClientes.java
antes de revisar essa aqui peço que revise a anterior
=> Requisito revisão da pull anterior (referente a issue #830)

Ericles/GerenciadorCliente.cs
Verificar se o código está seguindo todos os requisitos da issue!
#867
=> Add:: Adicionar na classe GerenciadorCliente métodos remover e alterar

Thiago/GerenciadorCliente.java
=> Classe Implementada. Resolve #883

Joanne/GerenciarCliente.py
Criado o gerenciarCliente com classes de inserir e consultar.
Resolve #907
=> Add: GerenciarCliente

Ericles/GerenciadorVenda.cs
Verificar se o código está seguindo todos os requisitos da issue #868 !
Revisem com cuidado, por favor!
=> ADD:: Criar a Classe GerenciadorVenda com pelo chama pelo menos um método de GerenciadorCliente

Joanne/GerenciarCliente.py
=> Add: Gerenciar Cliente com metodos remover e alterar cliente

Thiago/GerenciadorCliente.java
=> Métodos de alterar e remover adicionados. Resolve #917

Joanne/GerenciarCliente.py
Adicionados na classe GerenciadorCliente métodos remover e alterar, otimizado 
Resolve #919
=> Add: metodos remover e alterar 

Joanne/GerenciarVenda.py
Criar a Classe GerenciadorVenda com pelo chama pelo menos um método de GerenciadorCliente
Resolve #909
=> Add: Classe GerenciadorVenda

Kendy/GerenciadorCliente.java
=> Branch kendy 913

Milena/Cliente.java, Milena/GerenciadorCliente.java
=> Analisar classe de Gerenciador Cliente

Milena/GerenciadorCliente.java
Revisar a classe Gerenciador Cliente com os novos métodos de remover e alterar.
=> Revisar a classe Gerenciador Cliente

Vinicius/atividadeIndividual/GerenciadorCliente.java, Vinicius/atividadeIndividual/GerenciadorVenda.java
Boa noite.
Solicito a revisão do meu código relacionado a issue #942. 
Importante que a revisão seja realizada com atenção, para que não gere maiores problemas no ambiente de produção. 
Desde já, agradeço!
=> Implementação da classe "GerenciadorVenda" referente a issue #942

Vinicius/atividadeIndividual/GerenciadorCliente.java
A tarefa já está apta para ser revisada.
Por favor, realize a revisão desta tarefa com atenção. Para que assim, diminua as chances de gerar algum problema no ambiente de produção.
Desde já, agradeço.
=> Implementação dos métodos "alterarCliente" e "removerCliente" referente a issue #896

Kendy/GerenciadorCliente.java, Kendy/GerenciadorVenda.java
=> Branch kendy 914

MarcosDosea/GerenciadorCliente.java
=> Funcionalidades implementadas. Resolved #1011.

Bruna_Keila_Eduardo_Santos/GerenciadorCliente.java
Implementado conforme requisitado.
=> Método excluir cliente implementado. Resolved #1012

Paulo/ImprimirDados.java
=> Implementado o print para os dados do cliente. Resolved #1017

NataliaCosta/GerenciadorCliente.java.txt
=> Classe implementada. Resolved #1047

Gilmario/Desenvolvedor 01/GerenciadorCliente.java, Gilmario/Desenvolvedor 02/GerenciadorPagamentos.java, Gilmario/Desenvolvedor 02/GerenciadorVendas.java, Gilmario/ManterCliente/GerenciadorCliente.java
=> Implementação dos métodos(inserir e consultar clientes) concluída. Resolve #1037.

Gilmario/Desenvolvedor 01/GerenciadorCliente.java, Gilmario/Desenvolvedor 02/GerenciadorPagamentos.java, Gilmario/Desenvolvedor 02/GerenciadorVendas.java, Gilmario/ManterCliente/GerenciadorCliente.java
=> Branch gilmario 1039

NataliaCosta/GerenciadorCliente.java.txt
=> Implementado conforme especificado. Resolved #1048

NataliaCosta/GerenciadorVenda.java.txt
=> Implementado conforme especificado. Resolved #1049

JanainaFerreira/GerenciadorCliente.java
Classe com métodos inserir e consultar.
=> Criado GerenciadorCliente. Resolved #1070

JanainaFerreira/GerenciadorCliente.java
Métodos adicionados na classe GerenciadorCliente
=> Adicionados métodos remover e inserir. Resolved #1071

CaioEduardo/GerenciadorCliente.java
Criação da classe GerenciadorCliente com seus métodos remover e alterar.
=> commit tarefa 1

CaioEduardo/GerenciadorCliente.java
Adicionar na classe GerenciadorCliente métodos inserir e consultar. PS: acabei trocando os métodos.
=> Commit tarefa 2

CaioEduardo/GerenciadorVenda.java
Criar a Classe GerenciadorVenda com pelo chama pelo menos um método de GerenciadorCliente
=> Commit tarefa 3

VitorOliveira/gerenciadorCliente.java
criado  a classe GerenciamentoCliente e os metodos inserir e consultar.
=> passo 1 da atividade de gerenciamento de mudança. close #1102

VitorOliveira/gerenciadorCliente.java
adicionado os metodos remover e alterar da classe GerenciadorCliente.
=> Branch vitoroliveira 1103

VitorOliveira/GerenciadorVedas.java, VitorOliveira/gerenciadorCliente.java
Adicionado a classe GerenciamentoVendas.
=> Branch vitoroliveira 1104

JadsonTavares/GerenciadorCliente.java
=> Implementaçao feita. Resolve #1138.

Icaro/GerenciadorCliente.java
Criei Gerenciador cliente, por favor avaliar! Aguardo resposta
=> Create Gerenciado cliente. Closed #1143

Valdir Santana/GerenciadorCliente.java
=> Branch valdir santana   #1145

Icaro_Nadianne/GerenciadoVenda.java
=> Criar Gerenciador venda. Fechar #1149

verenilson/GerenciadorCliente.cs
=> Implementação dos métodos inserir e consultar!

verenilson/GerenciadorVenda.cs
Implementação feita com sucesso! hehe
=> A chamada de método solicitada foi feito com sucesso!

Icaro/GerenciadorCliente.java
Comentei o código. Confere se tá tudo ok, por favor.
=> Atualize Gerenciado Cliente. Fechar #1146

NadianneGalvão/GerenciadorCliente.java
Variáveis cliente adicionadas.
=> Nadianne gerenciador cliente consultar e inserir #1144

Valdir Santana/GerenciadorCliente.java
=> Resolved Issue#1151

NadianneGalvão/GerenciadorCliente.java, NadianneGalvão/GerenciadorVenda.java
=> Nadianne  gerenciador cliente remocer e alterar #1148

JadsonTavares/GerenciadorCliente.java, JadsonTavares/GerenciadorVenda.java
Por favor revisa o método criado.
=> implementaçao criada. Resolve #1140.

NadianneGalvão/GerenciadorCliente_Remover.java, NadianneGalvão/teste.java
=> Nadianne gerenciar vendas

Luis_Ribeiro/GerenciadorCliente.java
=> Adicionarnaclasse gerenciador clientemétodosremoverealterar#1119

Luis_Ribeiro/GerenciadorCliente.java, Luis_Ribeiro/GerenciadorVenda.java
=> Branch luis clr 1121

MarcosMorais/GerenciadorCliente.java
Nova funcionalidade de criar um novo cadastro de cliente e consultar os dados na base.
=> Adicionando implementação de gerência de clientes

MarcosMorais/GerenciadorCliente.java
Adicionado as funções de remover clientes e fazer alterações em seus cadastros na base de dados.
=> Adicionado métodos RemoverCliente e AlterarCliente

MarcosMorais/GerenciadorVenda.java
Criado a classe GerenciadorVenda e métodos FinalizarVenda e CancelarVenda.
=> Adicionado funcionalidade de finalizar e cancelar vendas

Carol_Lucas/GerenciadorCalculadora.java
Atualização da classe solicitada.
=> Atualizações GerenciadorCalculadora

Lucas_Werthein/GerenciadorCliente.java
Implementados os métodos inserir e consultar.
Closed #1369
=> Criar a classe GerenciadorCliente com método de inserir e consultar

CarolineLins/GerenciadorCliente.java
Foi implementado os métodos inserir e consultar.
=> Criação da classe GerenciadorCliente 

LucasWerthein/GerenciadorCliente.java
Inserido os métodos remover e alterar.
=>  Adicionar na classe GerenciadorCliente métodos remover e alterar

Lucas_Werthein/GerenciadorVenda.java
=> Criar a Classe GerenciadorVenda com um método para Finalizar e outro para Cancelar a venda.

GuilhermeLima/GerenciadorCliente.java
Adicionados os métodos inserir e consultar.
=> Regras de negócio para cliente para cliente.

Kaua/GerenciadorCliente.cs
Foi implementado o gerenciamento inicial do cliente, solicito revisão diante das boas práticas
=> Implementação inicial do gerenciamento de cliente, resolve #1378

Kaua/GerenciadorVenda.cs
Foi implementado o gerenciamento de vendas, solicito uma revisão para avaliar a implementação diante das boas práticas.
=> Implementado o gerenciamento de vendas, resolve #1381

Kaua/GerenciadorCliente.cs
Solicito revisão da implementação e validação diante das boas práticas.
=> Foi aprimorado o gerenciamento do cliente, resolve #1380

MatheusAndrade/GerenciadorCliente.java
=> Gerenciador Criado

MatheusAndrade/GerenciadorCliente.java
=> Classes criadas

MatheusAndrade/GerenciadorVenda.java
=> Classe GerenciadorVendas criado

FelipeMendonça/GerenciadorCliente.java.txt
Adicionado os metodos InserirCLientes e ConsultarClientes
=> Finalizado a classe GerencidorClientes

Vinicius-Lima/jogodavelha.txt
=> Branch vinicius 1413

Marlysson-SD/GerenciadorCliente.java
Criação de pasta e criação de método 
issue #1427
=> Criação e implementação

CamilaFontes/GerenciadorCliente.java
=> Cria nova classe para o projeto

Miguel-Ferreira/CriarMetodojava
=> Criar método de inserir e consultar

WalterSantos/GerenciadorCliente.cs
=> Adicionado classe GerenciadorCliente.cs

CamilaFontes/GerenciadorCliente.java
=> Cria novos métodos para a classe Gerenciador de Clientes

CamilaFontes/GerenciadorVenda.java
=> Cria classe de gerenciar vendas

Marlysson-SD/GerenciadorCliente.java
Métodos implementados
issue#1428
=> Métodos implementados

Marlysson-SD/GerenciadorVenda.java
=> Nova classe e métodos

Miguel-Ferreira/CriarMetodojava
=> Adicionar métodos remover e alterar

Miguel-Ferreira/Venda.java
=> Criar um método para Finalizar e Cancelar a venda

Miguel/CadastroCliente.java
=> implementar cadastro do cliente.

FelipeMendonça/GerenciadorCliente.java.txt
Foi adicionados os metodos  RemoverClientes e AtualizarClientes
=> Adicionado metodos na classe GerenciadorClientes #1407

IcaroReis/GerenciadorVenda.txt
Foi criado os métodos Cancelar Venda e Finalizar Venda
=> Criado Classe GerenciadorVenda.

Kaua/classea.cs
Foram realizados os testes referentes a issue #1338
=> Realizando o teste proposto em sala, resolve #1338

AlexandreMoreira/GerenciadorCliente.java
Foi implementado a classe GerenciadorCliente métodos remover e alterar na issue, Adicionar na classe GerenciadorCliente métodos remover e alterar #1454
=> Implementação da classe GerenciadorCliente métodos remover e alterar

AlexandreMoreira/GerenciadorCliente.java
Foi criado  a Classe GerenciadorVenda com um método para Finalizar e outro para Cancelar a venda
=> Foi alterado a Classe GerenciadorVenda

FelipeMendonça/GerenciadorCliente.java
Inserio os metodos InserirClietente e ConsultarCliente.
=> Adicionado o classe GerenciadorClientes.

Iago Liberato/GerenciadorCliente.java
Adicionado os métodos Inserir cliente e consultar cliente.
=> Adicionado Classe GerenciadorCliente.

FelipeMendonça/GerenciadorCliente.java
Adicionado os metodos RemoverCliente e AlterarCliente
=> adicionado novos metotos na classe GerenciadorClientes.

Iago Liberato/GerenciadorCliente.java
Adicionado o método Alterar e Remover cliente
=> Alteração do GerenciadorCliente.

FelipeMendonça/GerenciadorCliente.java
Adicionado os metodos RemoverCliente AtualizarClientes
=> Adicionado metodos requisitados

PedroDantas/GerenciadorCliente.java
=> Gerenciamento de clientes com operaçoes de inserir e consultar

FelipeMendonça/GerenciadorVendas.java
adicionados os metodos FinalizarVendas e CancelarVendas.
=> Adicionado a class GerenciadorVendas

Iago Liberato/GerenciadorVenda.java
Adicionado método de Finalizar e Cancelar venda
=> Adicionado GerenciadorVenda

PedroDantas/GerenciadorCliente.java
=> Adicionar operações de remover e alterar

PedroDantas/GerenciadorVenda.java
=> Implementar classe para gerenciamento de vendas

Igor Andrade/GerenciadorVenda.java
=> closes #1514

Hello World/Hello World.cbp, Hello World/Hello World.layout, Hello World/main.cpp
=> Implementaçao do hello world Closed #1334

CleomadsonMedeiros/GerenciadorCliente.java
Foi criada uma classe com o nome "GerenciadorCliente", dentro dela foram implementados os seguintes métodos: "adicionar" e "consultar"
=> Implementar funcionalidade para gerenciar um cliente

CleomadsonMedeiros/GerenciadorCliente.java, CleomadsonMedeiros/GerenciadorVenda.java
Foi criada a classe com o nome "GerenciadorVenda" e implementados os seguintes métodos: "finalizar" e "cancelar"
=> Implementar funcionalidade para gerenciar vendas

FernandaMirely/GerenciadorCliente.java
Feito métodos de inserir e consultar um cliente.
=> Implementar funcionalidade para gerenciar um cliente.

FernandaMirely/GerenciadorCliente.java
Foi feito os métodos de remover e alterar cliente
=> Adicionar funcionalidade para gerenciar um cliente.

Kewen/GerenciadorCliente.java
Os métodos foram adicionados na classe "GerenciadorCliente" como solicitado na issue #1663
=> Inserção dos métodos inserir e consultar

Kewen/GerenciadorCliente.java
Foram inseridos os devidos métodos na classe GerenciadorCliente
=> inserir os metodos remover alterar

Kewen/GerenciadorCliente.java, Kewen/GerenciadorVendas.java
Foram adicionados o métodos cancelar e finalizar para a classe "GerenciadorVenda"
=> insere os métodos cancelar e finalizar

IanTavares/GerenciadorCliente ( Inserir e  consultar).java, IanTavares/GerenciadorCliente alterar e remover.java, IanTavares/GerenciadorVenda.java
=> Criei a Classe GerenciadorVenda 

IanTavares/GerenciadorCliente ( Inserir e  consultar).java, IanTavares/GerenciadorCliente alterar e remover.java, IanTavares/GerenciadorVenda.java
=> Adicionei na classe GerenciadorCliente métodos remover e alterar closed #1658

RafaelLima/GerenciadorCliente.java
Funcionalidade implementada como solicitado.
=> Funcionalidade implementada como solicitado. Resolve #1673

RafaelLima/GerenciadorCliente.java
Funcionalidade de remover e alterar implementadas como solicitado.
=> Funcionalidades implementadas como solicitado. Resolve #1674

RafaelLima/GerenciadorCliente.java, RafaelLima/GerenciadorVenda.java
Funcionalidades de finalizar e cancelar venda implementadas issue #1675
=> Funcionalidades implementadas como solicitado. Resolve #1675

PedroDantas/GerenciadorCliente.java
Implementado gerenciador de cliente com os métodos de inserir e consultar cliente.
=> Impl inicial classe GerenciadorCliente - resolve #1679

TalyssonVasconcelos/GerenciadorCliente/src/GerenciadorVenda.java
=> Criado Classe GerenciadorVenda com um método para Finalizar e Cancelar

PedroDantas/GerenciadorCliente.java
Implementado os métodos de remover e alterar dentro do gerenciador de clientes. Favor revisar.
=> Impl metodos remover e alterar para cliente #1680

PedroDantas/GerenciadorVenda.java
Implementado o gerenciador de vendas com as opções de finalizar e cancelar uma venda específica. Revisar por gentileza.
=> Classe para gerenciamento de vendas - features de finalizar e cancelar uma venda #1681

TalyssonVasconcelos/GerenciadorCliente/src/GerenciadorCliente.java
=> Criado a classe GerenciadorCliente com método de inserir e consultar

LuizAugustoFarias/GerenciadorCliente.java
criado arquivo java GerenciadorCliente com o codigo abaixo:
`public class GerenciadorCliente {
public void inserir(String nome) {
System.out.println("Cliente " + nome + " inserido.");
}
public void consultar() {
System.out.println("Consulta de clientes realizada.");
}
}`
=> Adicionado arquivo GerenciadorCliente com metodos inserir e consultar

LuizAugustoFarias/GerenciadorCliente.java
adicionado os metodos de remover e alterar no arquivo gerenciadorcliente.java, codigo adicionado abaixo:
`public void remover(String nome) {
System.out.println("Cliente " + nome + " removido.");
}
public void alterar(String nomeAntigo, String nomeNovo) {
System.out.println("Cliente " + nomeAntigo + " alterado para " + nomeNovo + ".");
}`
=> Adicionados métodos remover e alterar na classe GerenciadorCliente

CassianoMenezes/GerenciadorCliente.java
=> Adicionado na classe GerenciadorCliente métodos remover e alterar

DiegoDias/GerenciadorCliente.java
=> Criado GerenciadorCliente e os metodos de inserir e alterar. Resolve#1713

DiegoDias/GerenciadorVenda.java
=> Criado a Classe GerenciadorVenda com os metodos finalizar e cancelar. Close #1715

ArthurAssis/GerenciadorCliente.java.txt
=> Classe GerenciadorCliente criada com seus devidos métodos de inserir e consultar.

Ana/GerenciadorVendas.java
=> Criada a classe de GerenciadorVendas.java

LuigiBarros/GerenciadorCliente.java
…s como pedido na Branch #1752
=> Foi implementada as funcionalidades de cadastro e consulta de cliente

TallyssonLuiz/GerenciadorCliente.py
Por vavor revisar e código solicitado na issue
=> Criado a classe GerenciadorCliente e seus métodos de inserir e consultar. Resolve #1760

TallyssonLuiz/GerenciadorCliente.py
Foram criados os dois métodos da Classe GerenciadorCliente, revisem por favor!!
=> Criados os métodos de remover e alterar. Resolve #1759

JoaoPedro/GerenciadorCliente.java
=> Classe GerenciadorCliente criada, além dos métodos inserir e consultar.

JoaoPedro/GerenciadorCliente.java
=> Ajustes feitos.

JoaoPedro/GerenciadorVenda.java
=> Classe e metodos criados
